### ISSUE TITLE
Change allowed response variables

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/dsm#1]
As suggested by @lenthomas:

`n`, `count` for count
`Nhat`, `abundance.est` for estimated abundance 
`Dhat`, `density.est` for estimated density

rather than refering to things that are counts as abundances.

**Comment by dill** [comment]
Implemented but deprecated responses need to be dropped.

**Comment by dill** [comment]
Suggest that we move to:

- `count` for count
- `abundance.est` for estimated abundance
- `density.est` for estimated density

as of 2.3.1. `n` especially seems like a poor choice above.

**Comment by lenthomas** [comment]
Fine by me -- Distance for Windows uses these already so no change needed there.

I didn't understand this comment "as of 2.3.1. n especially seems like a poor choice above".  Can you elaborate?

**Comment by dill** [comment]
This might just be an issue with my punctuation.

"as of 2.3.1." Relates to the previous bit (i.e., it could/should read "Suggest that, as of 2.3.1, we move to:". 

"`n` especially seems like a poor choice above." is a stand-alone. Having `n` as the response (when elsewhere it's referred to as e.g., the sample size for the segments in the `summary` output) seems confusing for users.

**Comment by lenthomas** [comment]
Aha, makes sense, thanks.  Yes, I'm fine with only allowing the long-form versions of these variables.

**Comment by dill** [comment]
fixed in 6b47fb674f4b89f28dfd5c6a5400966dbc9f9c8a
