### ISSUE TITLE
Defualt off.set argument in dsm.var.gam() throws error

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/dsm#22]
Leaving the offset value as the default (NULL) causes dsm.var.gam to throw an error.

I have changed the offset to 1 so it is using density by default.

But now I notice that dsm.var.prop and dsm.var.movblk do not provide a default value... perhaps instead the default value should be removed for dsm.var.gam? @dill

**Comment by dill** [comment]
dsm.var.* should crash if the offset is not supplied. Not sure why there 
is an inconsistency here. Better to remove any default values and have 
it crash on no input than have NULL trickle through the function and 
cause a weird non-transparent error.
