### ISSUE TITLE
dsm.var.prop() excludes Dhat as response and point transects

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsm#31]
Trying to run Gui's point transect dsm(); all goes well (after mgcv() hassle resolved, however, he uses the variance propagation method of computation and this stop() message is issued by dsm_varprop()
```
Only line transects are supported at the moment
```
Gui however, sent a completed analysis because he was using an earlier version of dsm() that did not have that error message. My uneducated examination of Gui's variance estimate using count as a response looks reasonable.

**Comment by dill** [comment]
Closing as point transects were implemented some time ago and `Dhat` response won't be added.
