### ISSUE TITLE
lazyeval R package

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/dsm#32]
I am trying to run dsm from a clean install of R, with the usual packages installed.  It gives me

Error: package or namespace load failed for 'dsm' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'lazyeval'

From this, I conclude that the package lazyeval is required.  I don't, however, see it mentioned in the DESCRIPTION file, nor in any file in the dsm tree.

Can you confirm that lazyeval is indeed required?  If so, are we sure we need it -- it's only on version 0.2.0 so possibly will change greatly in the future.  Are we storing up problems for later?  If we really do need it, then I'll add it to the Distance for windows distribution manifest.

**Comment by lenthomas** [comment]
@dill Same goes for packages tibble and rlang

**Comment by dill** [comment]
blurg, didn't realise this was the case...

```
> tools::package_dependencies("dsm", recursive=TRUE)
$dsm
 [1] "mgcv"         "mrds"         "numDeriv"     "nlme"         "ggplot2"
 [6] "statmod"      "digest"       "grid"         "gtable"       "MASS"
[11] "plyr"         "reshape2"     "scales"       "stats"        "tibble"
[16] "lazyeval"     "methods"      "graphics"     "Matrix"       "optimx"
[21] "Rsolnp"       "utils"        "lattice"      "grDevices"    "ucminf"
[26] "BB"           "Rcgmin"       "Rvmmin"       "minqa"        "setRNG"
[31] "dfoptim"      "svUnit"       "Rcpp"         "stringr"      "truncnorm"
[36] "parallel"     "RColorBrewer" "dichromat"    "munsell"      "labeling"
[41] "rlang"        "quadprog"     "colorspace"   "optextras"    "stringi"
[46] "magrittr"     "tools"
```

This seems to be `ggplot2`s fault:

```
> tools::package_dependencies("ggplot2", recursive=TRUE)
$ggplot2
 [1] "digest"       "grid"         "gtable"       "MASS"         "plyr"
 [6] "reshape2"     "scales"       "stats"        "tibble"       "lazyeval"
[11] "grDevices"    "graphics"     "utils"        "methods"      "Rcpp"
[16] "stringr"      "RColorBrewer" "dichromat"    "munsell"      "labeling"
[21] "rlang"        "colorspace"   "stringi"      "magrittr"     "tools"
```

Not sure what we can do about that though since we do need `ggplot2` but agree this number of dependencies is getting out of control...

How are you installing btw, is this just from a `.zip`?

**Comment by LHMarshall** [comment]
yes all the packages are distributed as .zip's with Distance

**Comment by lenthomas** [comment]
Thanks folks, I edited 
\Distance70\Misc\NEngineInterfaceUtilities\support.r 
to add in these packages, and also added them to the directory
\Distance70\Misc\NEngineInterfaceUtilities\Rpackages

@LHMarshall please note that it's vital to run the support.r function 
install.distance.packages(download.only=TRUE)
and put the downloaded packages into the Rpackages library (deleting those that are currently there), plus adding the latest version of mrds, dsm, DSsim in there, before packing up the install.  Since the definitive versions of the packages compiled with R 3.4.1 are not currently available, I have not done that.

One last thing -- I see that the package tweedie has been added to the required packages list in support.r.  Does anyone know why?  I don't see it in the list of required packages for dsm, above.  If it's required for one of the other packages, please can someone edit the support.r file to add an appropriate explanation?  (It has been added on the end of dsm, so I put it on a line of its own for now).  Or tell me and I can do it.  Thanks!

**Comment by dill** [comment]
tweedie is needed to get the rq residuals and IIRC a dependency for 
statmod (or at least needed for the bit of statmod we use.

**Comment by lenthomas** [comment]
Hmm
> package_dependencies("statmod",available.packages(),recursive=T)
$statmod
[1] "stats"    "graphics"

**Comment by lenthomas** [comment]
Aha:

statmod: Statistical Modeling

A collection of algorithms and functions to aid statistical modeling. Includes growth curve comparisons, limiting dilution analysis (aka ELDA), mixed linear models, heteroscedastic regression, inverse-Gaussian probability calculations, Gauss quadrature and a secure convergence algorithm for nonlinear models. Includes advanced generalized linear model functions that implement secure convergence, dispersion modeling and Tweedie power-law families.
Version: 	1.4.30
Depends: 	R (≥ 1.6.1)
Imports: 	stats, graphics
Suggests: 	MASS, tweedie

I love R

**Comment by LHMarshall** [comment]
It's suggested not depended on... but I added this as we need it... found that out due to error of not having it

https://cran.r-project.org/web/packages/statmod/index.html

**Comment by lenthomas** [comment]
Yup, I came to the same conclusion.  R really is a pain sometimes.  

Anyway, I'll close this, and add a suitable comment to the support.r file saying why we need tweedie
