### ISSUE TITLE
Possible issue in predict.dsm

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/dsm#33]
Thought I'd posted this one already -- but seemingly not, so here it is:

I believe there is an issue with predict.dsm when density is the response.  In a trial (below) I obtained an estimate of completely the wrong order of magnitude, when using count or est.N as responses works fine (and gives the same answer – in this case that’s expected given a CDS detection function).  Code below.

```
library(Distance)
library(dsm)

# load the Gulf of Mexico dolphin data (see ?mexdolphins)
data(mexdolphins)

# fit a detection function and look at the summary
hr.model <- ds(distdata, max(distdata$distance),
               key = "hr", adjustment = NULL)
summary(hr.model)
#[1] 28462.25

# fit a simple smooth of x and y to counts
mod1 <- dsm(count~s(x,y), hr.model, segdata, obsdata)
summary(mod1)
# predict over a grid
mod1.pred <- predict(mod1, preddata, preddata$area)
# calculate the predicted abundance over the grid
sum(mod1.pred)
#[1] 28462.25

# fit a simple smooth of x and y to estimated abundance
mod2 <- dsm(abundance.est~s(x,y), hr.model, segdata, obsdata)
summary(mod2)# predict over a grid
mod2.pred <- predict(mod2, preddata, preddata$area)
# calculate the predicted abundance over the grid
sum(mod2.pred)

# fit a simple smooth of x and y to estimated density
mod3 <- dsm(density~s(x,y), hr.model, segdata, obsdata, family=gaussian())
summary(mod3)
# predict over a grid
mod3.pred <- predict(mod3, preddata, preddata$area)
# calculate the predicted abundance over the grid
sum(mod3.pred)
#[1] 9.134999e-05
#Oops!

```

**Comment by dill** [comment]
(fwiw, now we have

```
> sum(mod3.pred)
[1] 24777.49
```

but note that `mod2` and `mod3` are rather different models with different estimated smooths...)

**Comment by lenthomas** [comment]
Awesome, thanks Dave.  I wasn't expecting the same results, just similar, so this is great.

**Comment by lenthomas** [comment]
Err... sorry, dude - not working fully yet.  Doesn't work for Dhat or density.est as response vars, but these are allowed according to the help (and code) for the dsm function.   See below.

```
library(Distance)
library(dsm)

# load the Gulf of Mexico dolphin data (see ?mexdolphins)
data(mexdolphins)

# fit a detection function and look at the summary
hr.model <- ds(distdata, max(distdata$distance),
               key = "hr", adjustment = NULL)

# fit a simple smooth of x and y to estimated density
mod3 <- dsm(density~s(x,y), hr.model, segdata, obsdata, family=gaussian())
mod3.pred <- predict(mod3, preddata, off.set=preddata$area)
sum(mod3.pred)
# [1] 24777.49
#This works

mod3 <- dsm(density.est~s(x,y), hr.model, segdata, obsdata, family=gaussian())
mod3.pred <- predict(mod3, preddata, off.set=preddata$area)
sum(mod3.pred)
#[1] 9.134999e-05
#Nope!

mod3 <- dsm(D~s(x,y), hr.model, segdata, obsdata, family=gaussian())
mod3.pred <- predict(mod3, preddata, off.set=preddata$area)
sum(mod3.pred)
# [1] 24777.49
#OK

mod3 <- dsm(Dhat~s(x,y), hr.model, segdata, obsdata, family=gaussian())
mod3.pred <- predict(mod3, preddata, off.set=preddata$area)
sum(mod3.pred)
#[1] 9.134999e-05
#Nope!

```

**Comment by dill** [comment]
On my list for tonight.

Though: I wonder if we should remove the Dhat and density.est options if
they actually do the same thing functionally as density and D? I'll
check and if so does this seem reasonable?

**Comment by lenthomas** [comment]
Hmm... I vote for keeping them. People may be using these tokens now (Distance certainly is, but that's quite easily changed) -- what is the reason for restricting the options?

**Comment by dill** [comment]
Only reasoning is that this happens and it's a pain :)

**Comment by lenthomas** [comment]
Hmm, yes, but I think we need to deprecate some options first, before just cutting them off!  Since for Abundance, allowable covars are Nhat, abundance.est then it makes sense for allowable options for density to be Dhat and density.est.  Feel free to deprecate the others if you like -- ie declare them as deprecated for this version and then delete on the next version.  Funnily, the two that I suggest deprecating are the two that work at present.  

I note that N can be used for count at present, which is another reason to get rid of D is it's inconsistent -- N is count but not estimated abundance; D is estimated density but not encounter rate.

**Comment by dill** [comment]
Let's move this discussion over to #1:
https://github.com/DistanceDevelopment/dsm/issues/1 as I think we had
thoughts about this before... (I think the suggestion there was based on
your preferences?)

**Comment by lenthomas** [comment]
Wow, yes, I see I've been repeating myself from 3 years ago...
Well, up to you if you implement that now or next version then (with an appropriate warning if people use the deprecated tokens for now).  In distance-for-windows, I use Dhat.
