### ISSUE TITLE
DSM model averaging 

### ISSUE THREAD

**Issue by deervale** [DistanceDevelopment/dsm#34]
Hi David, 
I want to do a model averaging on a DSM object. As it is a GAM and GAMs are supported by MuMIn package I was wondering how to do that. Is there a way to "remove" the ddf object from the model or to call just the GAM part of it in order to make it work? 
Thanks

**Comment by dill** [comment]
Apologies for the extremely late reply on this issue. For what it's worth, I don't know much about the MuMIn package. If it does support GAMs in general I'd say you can just assign the `$ddf` element of a `dsm` object to to be `NULL`, then it would be possible to use it. However, I don't think model averaging is necessarily a good angle. Better to find out what is causing model differences and use the shrinkage-based approaches available in `dsm`/`mgcv`. See [this report](https://github.com/bbolker/discretization/blob/master/discrete.pdf) for more arguments against model averaging-type approaches.
