### ISSUE TITLE
Environmetrics task view doesn't mention `dsm`

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/dsm#40]
Gavin Simpson maintains the task view.  https://cran.r-project.org/web/views/Environmetrics.html

He make this odd statement:
>Count data are corrected using detection function models fitted using mrds or Distance. Spatial models are constructed as in mgcv. 

without mentioning `dsm`

**Comment by dill** [comment]
Removed because `dsm` was archived ([see here](https://r-forge.r-project.org/scm/viewvc.php?view=rev&root=ctv&revision=3142)]). Have passed this on to Gavin now `dsm` is unarchived.

**Comment by dill** [comment]
[Fixed](https://cran.r-project.org/web/views/Environmetrics.html)
