### ISSUE TITLE
"dsm: Error while checking: invalid 'envir' argument" with R-devel

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/dsm#8]
With the development version of R (2015-07-07 r68640), the following error is generated when running `R CMD CHECK dsm_2.2.8.tar.gz`:

```
dsm: Error while checking: invalid 'envir' argument
```

The only other reference I can find to this is in [`pacman`](https://github.com/trinker/pacman/issues/66).

**Comment by erex** [comment]
supposedly it is in the Roxygen component of the function `generated.ds.uncertainty` l11-14, but what happens if you pull out the `note` in the documentation of that function?

**Comment by dill** [comment]
This doesn't seem to be the source of the issue...

**Comment by dill** [comment]
seems like running:

```r
Sys.setenv("_R_CHECK_CODE_USAGE_WITH_ONLY_BASE_ATTACHED_" = "TRUE")
tools:::.check_packages("dsm")
```

will allow one to reproduce the error in an interactive session.

**Comment by dill** [comment]
This bug no-longer shows up in (at least) R-devel 3.3.0 Under development (unstable) (2015/11/23, r69688).
